In [1]:
from PIL import Image
import requests
from transformers import Blip2Processor, Blip2ForConditionalGeneration
import torch

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

processor = Blip2Processor.from_pretrained("Salesforce/blip2-opt-2.7b")
model = Blip2ForConditionalGeneration.from_pretrained(
    "Salesforce/blip2-opt-2.7b", torch_dtype=torch.float16
)
model.to(device)

In [11]:
image = Image.open("/data/soyeonhong/GroundVQA/00d9a297-d967-4d28-8e5a-6b891814ec65/000000-blackbox.jpg").convert('RGB')

inputs = processor(images=image, return_tensors="pt").to(device, torch.float16)

generated_ids = model.generate(**inputs, max_length=100, min_length=30)
generated_text = processor.batch_decode(generated_ids, skip_special_tokens=True)[0].strip()
print(generated_text)

a kitchen with a stove, sink and a microwave on it. there is a person in the kitchen with a camera on it. the camera is looking down at the counter


In [1]:
from PIL import Image
import requests
from transformers import AutoProcessor, LlavaForConditionalGeneration
import torch

In [4]:
# Load model directly
from transformers import AutoProcessor, AutoModelForCausalLM

processor = AutoProcessor.from_pretrained("liuhaotian/llava-v1.6-vicuna-7b")
# model = AutoModelForCausalLM.from_pretrained("liuhaotian/llava-v1.6-vicuna-7b")

OSError: liuhaotian/llava-v1.6-vicuna-7b does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co/liuhaotian/llava-v1.6-vicuna-7b/tree/main' for available files.

In [4]:
prompt = "USER: <image>\ncan you answer the question 'What color was the napkin I used last?' ASSISTANT:"
image = Image.open("/data/soyeonhong/GroundVQA/00d9a297-d967-4d28-8e5a-6b891814ec65/000000.jpg").convert('RGB')

inputs = processor(text=prompt, images=image, return_tensors="pt")

# Generate outputs and get hidden states
with torch.no_grad():
    outputs = model.generate(**inputs, max_new_tokens=1024, output_hidden_states=False, return_dict_in_generate=True)

# # Decode the generated text
generated_text = processor.batch_decode(outputs.sequences, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]

# # Get the hidden states from the outputs
# hidden_states = outputs.hidden_states

# # If you want the hidden states of the last layer
# last_hidden_states = hidden_states[-1]

print(generated_text)
# print(last_hidden_states)

USER:  
can you answer the question 'What color was the napkin I used last?' ASSISTANT: Green


In [16]:
last_hidden_states

(tensor([[[-0.0133, -0.0371,  0.0014,  ...,  0.0227, -0.0123,  0.0082]]]),
 tensor([[[-0.0177, -0.0506,  0.0083,  ...,  0.0422, -0.0128,  0.0156]]]),
 tensor([[[-0.0381, -0.0740,  0.0287,  ...,  0.0660, -0.0030,  0.0268]]]),
 tensor([[[-0.0194, -0.0902,  0.0081,  ...,  0.0521,  0.0044,  0.0863]]]),
 tensor([[[ 0.0165, -0.1421,  0.1044,  ...,  0.0525, -0.0353,  0.0577]]]),
 tensor([[[ 0.1394, -0.0991,  0.0955,  ..., -0.0331, -0.0455,  0.0993]]]),
 tensor([[[-0.0126, -0.0087,  0.1380,  ..., -0.1008, -0.0343,  0.1179]]]),
 tensor([[[ 0.0956, -0.1185,  0.1781,  ...,  0.0473,  0.0051,  0.1366]]]),
 tensor([[[ 0.0674, -0.0065,  0.1042,  ..., -0.0474,  0.1130,  0.1767]]]),
 tensor([[[ 0.0523,  0.1725,  0.1217,  ..., -0.0140,  0.2941,  0.0706]]]),
 tensor([[[-0.0090,  0.2269,  0.2821,  ..., -0.1824,  0.4301,  0.2635]]]),
 tensor([[[ 0.2562,  0.1102,  0.1080,  ..., -0.0963,  0.3800,  0.1598]]]),
 tensor([[[0.1440, 0.1648, 0.2334,  ..., 0.0815, 0.2092, 0.2055]]]),
 tensor([[[ 0.2873, -0.0585,  0

In [18]:
inputs

{'input_ids': tensor([[    1,  3148,  1001, 29901, 29871, 32000, 29871,    13,  5618,   508,
           366,  1074, 29973,   319,  1799,  9047, 13566, 29901]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]), 'pixel_values': tensor([[[[-0.5660, -0.9456, -1.1353,  ..., -0.3616, -0.3616, -0.3616],
          [-0.6098, -0.9602, -1.1645,  ..., -0.3616, -0.3616, -0.3616],
          [-0.6536, -1.0039, -1.2375,  ..., -0.3616, -0.3616, -0.3616],
          ...,
          [-0.3032, -0.2886, -0.2886,  ...,  0.1055,  0.1055,  0.1055],
          [-0.3032, -0.2886, -0.2886,  ...,  0.1055,  0.1055,  0.1055],
          [-0.3032, -0.2886, -0.2886,  ...,  0.1055,  0.1055,  0.1055]],

         [[ 1.9248,  1.8047,  1.9098,  ..., -0.5215, -0.5215, -0.5215],
          [ 1.9398,  1.8047,  1.8648,  ..., -0.5215, -0.5215, -0.5215],
          [ 1.9848,  1.8348,  1.8198,  ..., -0.5215, -0.5215, -0.5215],
          ...,
          [-0.6865, -0.6715, -0.6715,  ..., -0.1012, -0.101

In [28]:
inputs.input_ids

tensor([[    1,  3148,  1001, 29901, 29871, 32000, 29871,    13,  5618,   508,
           366,  1074, 29973,   319,  1799,  9047, 13566, 29901]])

In [20]:
inputs['pixel_values'].shape

torch.Size([1, 3, 336, 336])

In [22]:
print(model.tokenizer)

AttributeError: 'LlavaForConditionalGeneration' object has no attribute 'tokenizer'

In [24]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
tokenizer = AutoTokenizer.from_pretrained("llava-hf/llava-1.5-7b-hf")

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [26]:
print(tokenizer)

LlamaTokenizerFast(name_or_path='llava-hf/llava-1.5-7b-hf', vocab_size=32000, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='left', truncation_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'pad_token': '<pad>'}, clean_up_tokenization_spaces=False),  added_tokens_decoder={
	0: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("<s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32000: AddedToken("<image>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32001: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}


In [27]:
tokenizer('<image>')

{'input_ids': [1, 32000], 'attention_mask': [1, 1]}